import { writeFileSync } from 'fs'
import { join } from 'path'
import { describe, expect, it } from 'vitest'
import { getRemotes, saveRemote, removeRemote, setUpstream, publishBranch, getBranches } from '../src/git-worker/operations'
import { git, initRepo, trackTempDirs } from './helpers/git-fixture'

const temp = trackTempDirs()

describe('remote management', () => {
  it('adds and edits distinct fetch/push URLs, then removes the override and remote', async () => {
    const repo = await initRepo(temp('gm-remotes-'))
    await saveRemote(repo, { repoPath: repo, name: 'origin', url: 'https://example.com/one.git', pushUrl: 'git@example.com:one.git', create: true })
    expect(await getRemotes(repo)).toEqual([{ name: 'origin', fetchUrl: 'https://example.com/one.git', pushUrl: 'git@example.com:one.git' }])
    await saveRemote(repo, { repoPath: repo, name: 'origin', url: 'https://example.com/two.git', pushUrl: '', create: false })
    expect(await getRemotes(repo)).toEqual([{ name: 'origin', fetchUrl: 'https://example.com/two.git', pushUrl: 'https://example.com/two.git' }])
    await expect(saveRemote(repo, { repoPath: repo, name: 'origin', url: 'https://other.invalid', create: true })).rejects.toThrow(/already exists/)
    await expect(saveRemote(repo, { repoPath: repo, name: '--upload-pack=bad', url: 'https://example.com', create: true })).rejects.toThrow(/Remote names/)
    await expect(saveRemote(repo, { repoPath: repo, name: 'safe', url: '--config=bad', create: true })).rejects.toThrow(/valid Git remote/)
    await removeRemote(repo, 'origin')
    expect(await getRemotes(repo)).toEqual([])
  })

  it('publishes to an explicit remote and branch, and changes or clears tracking', async () => {
    const repo = await initRepo(temp('gm-publish-'))
    const first = temp('gm-publish-origin-')
    const second = temp('gm-publish-backup-')
    await git(first, 'init', '--bare')
    await git(second, 'init', '--bare')
    await saveRemote(repo, { repoPath: repo, name: 'origin', url: first, create: true })
    await saveRemote(repo, { repoPath: repo, name: 'backup', url: second, create: true })
    expect(await publishBranch(repo, 'backup', 'release/demo')).toEqual({ outcome: 'done' })
    const head = (await git(repo, 'rev-parse', 'HEAD')).trim()
    expect((await git(second, 'rev-parse', 'refs/heads/release/demo')).trim()).toBe(head)
    expect((await getBranches(repo)).find((branch) => branch.current)?.upstream).toBe('backup/release/demo')
    expect((await git(first, 'for-each-ref', 'refs/heads')).trim()).toBe('')
    await setUpstream(repo, { repoPath: repo, branch: 'main', upstream: null })
    expect((await getBranches(repo)).find((branch) => branch.current)?.upstream).toBeNull()
    await setUpstream(repo, { repoPath: repo, branch: 'main', upstream: 'backup/release/demo' })
    expect((await getBranches(repo)).find((branch) => branch.current)?.upstream).toBe('backup/release/demo')
    writeFileSync(join(repo, 'README.md'), '# updated\n')
    await git(repo, 'commit', '-am', 'update')
    await publishBranch(repo, 'backup', 'release/demo')
    expect((await git(second, 'rev-parse', 'release/demo')).trim()).toBe((await git(repo, 'rev-parse', 'HEAD')).trim())
    await expect(publishBranch(repo, 'backup', '--bad')).rejects.toThrow(/Invalid destination/)
  }, 30000)

  it('pushes to another destination while preserving an upstream that still lacks local commits', async () => {
    const repo = await initRepo(temp('gm-push-to-'))
    const origin = temp('gm-push-to-origin-')
    const backup = temp('gm-push-to-backup-')
    await git(origin, 'init', '--bare')
    await git(backup, 'init', '--bare')
    await saveRemote(repo, { repoPath: repo, name: 'origin', url: origin, create: true })
    await saveRemote(repo, { repoPath: repo, name: 'backup', url: backup, create: true })
    await publishBranch(repo, 'origin', 'main')
    const oldTip = (await git(origin, 'rev-parse', 'main')).trim()
    await git(repo, 'commit', '--allow-empty', '-m', 'local work')

    expect(await publishBranch(repo, 'backup', 'release/demo', false, 'main')).toEqual({ outcome: 'done' })
    expect((await git(backup, 'rev-parse', 'release/demo')).trim()).toBe((await git(repo, 'rev-parse', 'HEAD')).trim())
    expect((await git(origin, 'rev-parse', 'main')).trim()).toBe(oldTip)
    const current = (await getBranches(repo)).find((branch) => branch.current)
    expect(current?.upstream).toBe('origin/main')
    expect(current?.ahead).toBe(1)

    expect(await publishBranch(repo, 'backup', 'release/demo', true, 'main')).toEqual({ outcome: 'done' })
    expect((await getBranches(repo)).find((branch) => branch.current)?.upstream).toBe('backup/release/demo')
  }, 30000)

  it('rejects a changed source branch, detached HEAD and branches with no commits before pushing', async () => {
    const repo = await initRepo(temp('gm-publish-source-'))
    const remote = temp('gm-publish-source-remote-')
    await git(remote, 'init', '--bare')
    await saveRemote(repo, { repoPath: repo, name: 'origin', url: remote, create: true })
    await git(repo, 'checkout', '-b', 'other')
    await expect(publishBranch(repo, 'origin', 'main', true, 'main')).rejects.toThrow(/current branch changed/)
    expect((await git(remote, 'for-each-ref', 'refs/heads')).trim()).toBe('')
    await git(repo, 'checkout', '--detach')
    await expect(publishBranch(repo, 'origin', 'main')).rejects.toThrow(/HEAD is detached/)

    const unborn = await initRepo(temp('gm-publish-unborn-'), { initialCommit: false })
    await saveRemote(unborn, { repoPath: unborn, name: 'origin', url: remote, create: true })
    await expect(publishBranch(unborn, 'origin', 'main')).rejects.toThrow(/Create a commit/)
    expect((await git(remote, 'for-each-ref', 'refs/heads')).trim()).toBe('')
  }, 30000)

  it('keeps tracking and remote commits intact after cancellation and a rejected explicit push', async () => {
    const repo = await initRepo(temp('gm-publish-failure-'))
    const remote = temp('gm-publish-failure-remote-')
    await git(remote, 'init', '--bare')
    await saveRemote(repo, { repoPath: repo, name: 'origin', url: remote, create: true })
    await publishBranch(repo, 'origin', 'main')
    const oldTip = (await git(repo, 'rev-parse', 'HEAD')).trim()
    const cancellation = new AbortController()
    cancellation.abort()
    expect(await publishBranch(repo, 'origin', 'cancelled', true, 'main', { signal: cancellation.signal })).toEqual({ outcome: 'cancelled' })
    expect((await getBranches(repo)).find((branch) => branch.current)?.upstream).toBe('origin/main')
    expect((await git(remote, 'for-each-ref', 'refs/heads/cancelled')).trim()).toBe('')

    await git(repo, 'commit', '--allow-empty', '-m', 'remote work')
    await publishBranch(repo, 'origin', 'main')
    const remoteTip = (await git(remote, 'rev-parse', 'main')).trim()
    await git(repo, 'reset', '--hard', oldTip)
    await git(repo, 'commit', '--allow-empty', '-m', 'different local work')
    await expect(publishBranch(repo, 'origin', 'main', false, 'main')).rejects.toThrow(/rejected/)
    expect((await git(remote, 'rev-parse', 'main')).trim()).toBe(remoteTip)
    expect((await getBranches(repo)).find((branch) => branch.current)?.upstream).toBe('origin/main')
  }, 30000)

  it('changes and clears tracking on another local branch without checking it out', async () => {
    const repo = await initRepo(temp('gm-tracking-other-'))
    const remote = temp('gm-tracking-other-remote-')
    await git(remote, 'init', '--bare')
    await saveRemote(repo, { repoPath: repo, name: 'origin', url: remote, create: true })
    await publishBranch(repo, 'origin', 'main')
    await git(repo, 'branch', 'feature')
    await setUpstream(repo, { repoPath: repo, branch: 'feature', upstream: 'origin/main' })
    const branches = await getBranches(repo)
    expect(branches.find((branch) => branch.current)?.name).toBe('main')
    expect(branches.find((branch) => branch.name === 'feature')?.upstream).toBe('origin/main')
    await setUpstream(repo, { repoPath: repo, branch: 'feature', upstream: null })
    expect((await getBranches(repo)).find((branch) => branch.name === 'feature')?.upstream).toBeNull()
    await expect(setUpstream(repo, { repoPath: repo, branch: 'feature', upstream: 'origin/missing' })).rejects.toThrow()
  }, 30000)
})
