/**
 * Shared map of git-worker RPC method names → operation functions.
 * Used by both utilityProcess handlers and the inline client fallback.
 */
import {
  applyPartial,
  cherryPickCommit,
  countCommitsAfter,
  createTag,
  deleteTag,
  getSequencerOp,
  pushTag,
  resetToCommit,
  revertCommit,
  sequencerStep,
  checkoutRef,
  checkoutRemoteBranch,
  cloneRepository,
  commit,
  createBranch,
  deleteBranch,
  fetchRemote,
  filterIgnoredPaths,
  getBranches,
  getCommitDetail,
  getFileDiff,
  getGitDirs,
  getGitIdentity,
  getMergeSides,
  getRemoteBranches,
  getStatus,
  getWatchFingerprint,
  getWorktreeInfo,
  pruneWorktree,
  getWorkingTreeDiff,
  createRepository,
  getDefaultBranchName,
  getEnclosingWorkTree,
  inspectRepoForRemoval,
  inspectRepository,
  isMergeInProgress,
  isRebaseInProgress,
  listConflictFiles,
  listStashes,
  loadHistory,
  mergeAbort,
  mergeRef,
  planDiscard,
  pullRemote,
  pushRemote,
  rebaseAbort,
  rebaseContinue,
  rebaseOnto,
  rebaseSkip,
  resolveConflictSide,
  restoreWorktree,
  saveMergeResult,
  setGitIdentity,
  stagePaths,
  stashApply,
  stashDrop,
  stashPop,
  stashSave,
  unstagePaths
} from './operations'

export const GIT_METHODS = {
  inspectRepository,
  createRepository,
  getDefaultBranchName,
  getEnclosingWorkTree,
  cloneRepository,
  getGitDirs,
  loadHistory,
  getCommitDetail,
  getFileDiff,
  getWatchFingerprint,
  getWorktreeInfo,
  pruneWorktree,
  getWorkingTreeDiff,
  getStatus,
  filterIgnoredPaths,
  getBranches,
  getRemoteBranches,
  stagePaths,
  unstagePaths,
  applyPartial,
  planDiscard,
  restoreWorktree,
  commit,
  fetchRemote,
  pullRemote,
  pushRemote,
  checkoutRef,
  checkoutRemoteBranch,
  createBranch,
  mergeRef,
  rebaseOnto,
  rebaseContinue,
  rebaseAbort,
  rebaseSkip,
  isRebaseInProgress,
  isMergeInProgress,
  mergeAbort,
  deleteBranch,
  cherryPickCommit,
  revertCommit,
  getSequencerOp,
  sequencerStep,
  countCommitsAfter,
  resetToCommit,
  createTag,
  deleteTag,
  pushTag,
  stashSave,
  listStashes,
  stashApply,
  stashPop,
  stashDrop,
  listConflictFiles,
  getMergeSides,
  saveMergeResult,
  resolveConflictSide,
  getGitIdentity,
  setGitIdentity,
  inspectRepoForRemoval
} as const

export type GitMethodName = keyof typeof GIT_METHODS

/** Operations that take `{ signal, onProgress }` as their last argument: they report progress and can be cancelled. */
export const CANCELLABLE_GIT_METHODS = ['fetchRemote', 'pullRemote', 'pushRemote', 'pushTag', 'cloneRepository'] as const
export type CancellableGitMethod = (typeof CANCELLABLE_GIT_METHODS)[number]

export function getGitMethod(method: string): ((...args: never[]) => unknown) | undefined {
  return GIT_METHODS[method as GitMethodName] as ((...args: never[]) => unknown) | undefined
}
