/**
 * Shared map of git-worker RPC method names → operation functions.
 * Used by both utilityProcess handlers and the inline client fallback.
 */
import {
  checkoutRef,
  checkoutRemoteBranch,
  cloneRepository,
  commit,
  createBranch,
  deleteBranch,
  fetchRemote,
  filterIgnoredPaths,
  getBranches,
  getCommitDetail,
  getFileDiff,
  getGitIdentity,
  getMergeSides,
  getRemoteBranches,
  getStatus,
  getWorkingTreeDiff,
  initRepository,
  inspectRepoForRemoval,
  inspectRepository,
  isMergeInProgress,
  isRebaseInProgress,
  listConflictFiles,
  listStashes,
  loadHistory,
  mergeAbort,
  mergeRef,
  planDiscard,
  pullRemote,
  pushRemote,
  rebaseAbort,
  rebaseContinue,
  rebaseOnto,
  rebaseSkip,
  resolveConflictSide,
  restoreWorktree,
  saveMergeResult,
  setGitIdentity,
  stagePaths,
  stashApply,
  stashDrop,
  stashPop,
  stashSave,
  unstagePaths
} from './operations'

export const GIT_METHODS = {
  inspectRepository,
  initRepository,
  cloneRepository,
  loadHistory,
  getCommitDetail,
  getFileDiff,
  getWorkingTreeDiff,
  getStatus,
  filterIgnoredPaths,
  getBranches,
  getRemoteBranches,
  stagePaths,
  unstagePaths,
  planDiscard,
  restoreWorktree,
  commit,
  fetchRemote,
  pullRemote,
  pushRemote,
  checkoutRef,
  checkoutRemoteBranch,
  createBranch,
  mergeRef,
  rebaseOnto,
  rebaseContinue,
  rebaseAbort,
  rebaseSkip,
  isRebaseInProgress,
  isMergeInProgress,
  mergeAbort,
  deleteBranch,
  stashSave,
  listStashes,
  stashApply,
  stashPop,
  stashDrop,
  listConflictFiles,
  getMergeSides,
  saveMergeResult,
  resolveConflictSide,
  getGitIdentity,
  setGitIdentity,
  inspectRepoForRemoval
} as const

export type GitMethodName = keyof typeof GIT_METHODS

export function getGitMethod(method: string): ((...args: never[]) => unknown) | undefined {
  return GIT_METHODS[method as GitMethodName] as ((...args: never[]) => unknown) | undefined
}
